dist: trusty

sudo: required

language: java

jdk: openjdk11

install: true

cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

before_script:
    - ./gradlew --version

script:
    - TERM=dumb ./gradlew build --scan

deploy:
  # Deploy snapshots on every commit made to master
  - provider: script
    # script: ./gradlew publish -PsonatypeUsername=$SONATYPE_USERNAME -PsonatypePassword=$SONATYPE_PASSWORD
    # Test signing with snapshot releases
    script: sh .ci/release.sh
    skip_cleanup: true
    on:
      branch: master
      
  # Deploy releases on every tag push
  - provider: script
    script: sh .ci/release.sh
    skip_cleanup: true
    on:
      tags: true
